export type {
    WorkspaceJson,
    Model,
    Person,
    SoftwareSystem,
    Container,
    Group,
    Relationship,
    Views,
    StructurizrView,
    ViewElement,
    ViewRelationship,
    AutoLayout,
    Configuration,
    Styles,
    ElementStyle,
    RelationshipStyle,
    ElementType,
    ResolvedElement,
} from '@c4/c4-parser'
